service: serverless-react-boilerplate

# plugins:
#   - serverless-webpack

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: us-east-1

functions:
  lambda:
    handler: dist/lambda.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'

# custom:
#   webpackIncludeModules: true
